<?php

namespace App\Support\Runs;

/**
 * How many Alerts a Run starts with, and what they do to a card.
 *
 * Alerts are the pressure gauge of a Run. They are generated once at the start
 * from how many Runners came and what they are already wanted for, they make
 * every Protection Card harder as they accumulate, and Security may spend them
 * as temporary Credits (rulebook 3.4.1, 3.4.2).
 *
 * Both curves are triangular numbers. The group-size bonus is the printed list
 * and then n(n+1)/2 - 10 for every size past it; the strength curve steps at
 * 1, 3, 6, 10, 15 and so on. The rulebook tabulates the first to six Runners
 * and the second to six Alerts and stops printing, but the rule carries on and
 * this is it, so both are answered for any number rather than handed back as
 * an open question.
 *
 * Every method still takes an override, because Control can overrule any number
 * in the game - not because these two are uncertain.
 */
class AlertSchedule
{
    /**
     * The group-size bonus the rulebook prints, by number of Runners.
     *
     * @var array<int, int>
     */
    public const PRINTED_GROUP_BONUS = [
        1 => 0,
        2 => 1,
        3 => 2,
        4 => 4,
        5 => 7,
        6 => 11,
    ];

    /**
     * The last group size the rulebook actually gives a number for.
     */
    public const PRINTED_UP_TO = 6;

    /**
     * Alerts generated by the size of the group.
     *
     * The printed list to six Runners, and the triangular numbers after it:
     * n(n+1)/2 - 10, so a seventh Runner costs 18 and an eighth 26.
     *
     * The formula is not a closed form of the printed list and is not meant to
     * be - it meets it at six (21 - 10 = 11) and disagrees with every row above
     * that, five Runners coming out as 5 where the list says 7. So the list is
     * consulted first and the formula only ever answers past the end of it.
     *
     * A solo Runner is the exception rather than the start of the run: they
     * bring no bonus at all, which is the whole reason to run alone.
     */
    public static function forGroupSize(int $runners, ?int $override = null): int
    {
        if ($override !== null) {
            return max(0, $override);
        }

        if ($runners <= 1) {
            return 0;
        }

        return self::PRINTED_GROUP_BONUS[$runners]
            ?? ((int) ($runners * ($runners + 1) / 2) - 10);
    }

    /**
     * Alerts generated by the Tags the Runners are carrying.
     *
     * One per Tag, counted across the whole group. This is what makes a Tag
     * expensive long after the Run that gave it to you - and why removing one
     * costs 3 Credits and is worth it.
     *
     * @param  array<int, int>  $tagsPerRunner
     */
    public static function forTags(array $tagsPerRunner): int
    {
        return array_sum(array_map(static fn (int $tags): int => max(0, $tags), $tagsPerRunner));
    }

    /**
     * Everything a Run opens with.
     *
     * Generated once, at the beginning, from the Tags held at that moment
     * (3.4.1) - a Tag taken during the Run does not retroactively add to this,
     * it makes the next Run worse.
     *
     * @param  array<int, int>  $tagsPerRunner
     */
    public static function atStart(array $tagsPerRunner, ?int $groupOverride = null): int
    {
        return self::forTags($tagsPerRunner)
            + self::forGroupSize(count($tagsPerRunner), $groupOverride);
    }

    /**
     * How much every Protection Card is strengthened by the Alerts standing.
     *
     * The thresholds are the triangular numbers: 1, 3, 6 Alerts for +1, +2, +3,
     * then 10 and 15 and so on. Read the other way round, the bonus is the
     * largest k whose k(k+1)/2 is no more than the Alerts standing.
     *
     * Note this rises with the Alerts Security is holding, so spending them
     * makes the rest of the Facility easier. That tension is the point.
     *
     * @return int<0, max>
     */
    public static function strengthBonus(int $alerts, ?int $override = null): int
    {
        if ($override !== null) {
            return max(0, $override);
        }

        $bonus = 0;
        $threshold = 1;

        while ($alerts >= $threshold) {
            $bonus++;
            $threshold += $bonus + 1;
        }

        return $bonus;
    }

    /**
     * The number of Alerts at which the next point of strength arrives.
     *
     * For the interface rather than the rules: a Security player deciding
     * whether to spend wants to know how close the Runners are to making every
     * remaining card harder.
     */
    public static function nextStrengthThreshold(int $alerts): int
    {
        $bonus = self::strengthBonus($alerts) + 1;

        return (int) ($bonus * ($bonus + 1) / 2);
    }
}
