<?php

namespace App\Support\Runs;

/**
 * How many Alerts a Run starts with, and what they do to a card.
 *
 * Alerts are the pressure gauge of a Run. They are generated once at the start
 * from how many Runners came and what they are already wanted for, they make
 * every Protection Card harder as they accumulate, and Security may spend them
 * as temporary Credits (rulebook 3.4.1, 3.4.2).
 *
 * Both curves here run past where the rulebook stops, and both extensions are
 * readings rather than rules. The book tabulates the group-size bonus to six
 * Runners and then says "See help sheet on the day", and the strength curve to
 * six Alerts and then "And so on". So every method takes an override, and
 * Control's number always wins: this is exactly the case CLAUDE.md means by
 * exposing a value for Control to set rather than deriving one.
 */
class AlertSchedule
{
    /**
     * The group-size bonus the rulebook prints, by number of Runners.
     *
     * @var array<int, int>
     */
    public const PRINTED_GROUP_BONUS = [
        1 => 0,
        2 => 1,
        3 => 2,
        4 => 4,
        5 => 7,
        6 => 11,
    ];

    /**
     * The last group size the rulebook actually gives a number for.
     */
    public const PRINTED_UP_TO = 6;

    /**
     * Alerts generated by the size of the group.
     *
     * The printed run is 0, 1, 2, 4, 7, 11, whose differences from three
     * Runners onwards are 1, 2, 3, 4 - so each extra Runner past the second
     * costs one more Alert than the last did, and the closed form for two or
     * more is 1 + (n-2)(n-1)/2. That reproduces every printed value and is what
     * a seventh Runner (16) and an eighth (22) get.
     *
     * A solo Runner is the exception rather than the start of the run: they
     * bring no bonus at all, which is the whole reason to run alone.
     */
    public static function forGroupSize(int $runners, ?int $override = null): int
    {
        if ($override !== null) {
            return max(0, $override);
        }

        if ($runners <= 1) {
            return 0;
        }

        return self::PRINTED_GROUP_BONUS[$runners]
            ?? 1 + (int) (($runners - 2) * ($runners - 1) / 2);
    }

    /**
     * Whether a group is big enough that the bonus is our arithmetic rather
     * than the rulebook's table.
     *
     * Worth saying out loud on screen: past six Runners the book sends Control
     * to a help sheet, so the number the application shows is a proposal.
     */
    public static function groupBonusIsExtrapolated(int $runners): bool
    {
        return $runners > self::PRINTED_UP_TO;
    }

    /**
     * Alerts generated by the Tags the Runners are carrying.
     *
     * One per Tag, counted across the whole group. This is what makes a Tag
     * expensive long after the Run that gave it to you - and why removing one
     * costs 3 Credits and is worth it.
     *
     * @param  array<int, int>  $tagsPerRunner
     */
    public static function forTags(array $tagsPerRunner): int
    {
        return array_sum(array_map(static fn (int $tags): int => max(0, $tags), $tagsPerRunner));
    }

    /**
     * Everything a Run opens with.
     *
     * Generated once, at the beginning, from the Tags held at that moment
     * (3.4.1) - a Tag taken during the Run does not retroactively add to this,
     * it makes the next Run worse.
     *
     * @param  array<int, int>  $tagsPerRunner
     */
    public static function atStart(array $tagsPerRunner, ?int $groupOverride = null): int
    {
        return self::forTags($tagsPerRunner)
            + self::forGroupSize(count($tagsPerRunner), $groupOverride);
    }

    /**
     * How much every Protection Card is strengthened by the Alerts standing.
     *
     * The printed thresholds are 1, 3 and 6 Alerts for +1, +2 and +3, which are
     * the triangular numbers - the fourth step is 10 Alerts and the fifth 15.
     * Read the other way round, the bonus is the largest k whose k(k+1)/2 is no
     * more than the Alerts standing.
     *
     * Note this rises with the Alerts Security is holding, so spending them
     * makes the rest of the Facility easier. That tension is the point.
     */
    public static function strengthBonus(int $alerts, ?int $override = null): int
    {
        if ($override !== null) {
            return max(0, $override);
        }

        $bonus = 0;
        $threshold = 1;

        while ($alerts >= $threshold) {
            $bonus++;
            $threshold += $bonus + 1;
        }

        return $bonus;
    }

    /**
     * The number of Alerts at which the next point of strength arrives.
     *
     * For the interface rather than the rules: a Security player deciding
     * whether to spend wants to know how close the Runners are to making every
     * remaining card harder.
     */
    public static function nextStrengthThreshold(int $alerts): int
    {
        $bonus = self::strengthBonus($alerts) + 1;

        return (int) ($bonus * ($bonus + 1) / 2);
    }
}
