<?php

namespace App\Support;

use App\Enums\ResearchCardRestriction;

/**
 * The game's technology list - the tech trees of rulebook 3.2.2 - applied to
 * every new game by App\Actions\SeedTechnologies.
 *
 * Each Corporation gets its own tree plus the technologies common to all of
 * them, which is what the tree key on each row says. A technology's costs are
 * the four Research Point suits, its prerequisites are the technologies that
 * have to be researched first, and where it names a Facility type the resulting
 * card can only be housed there (3.2.2, footnote 7).
 *
 * Codes carry the tree in their second letter, but not reliably - Gordon and
 * Genetic Equity both take a G - so the tree here is the column from the card
 * sheet rather than something read off the code. The code is still what
 * identifies a card and finds its artwork (see App\Support\CardImage).
 *
 * What a technology *does* is the text printed on it. Some of those effects are
 * mechanical - "Unlock: Keresh" makes a Protection Card buyable, "Unlock: Power
 * facility" adds a Facility type - but the research game that spends the points
 * is not built, so nothing here is computed. Control reads the words and moves
 * the numbers, which is the same rule the Facility type sheet follows.
 *
 * Prerequisites are stored as the titles printed on the card rather than as
 * foreign keys. A title is what a Research player shows Research Control
 * (footnote 6), and Control may edit or add technologies mid-game, so a
 * prerequisite naming a card that does not exist yet has to stay nameable.
 *
 * Split technologies (3.2.7) are printed as "Power (Part 1/4)" and carry that in
 * their titles. The rulebook gives them different rules for the owner and for a
 * thief, which belongs to the research game rather than to this catalogue.
 */
class TechnologyBlueprint
{
    /**
     * Technologies every Corporation's tree contains.
     */
    public const COMMON = 'standard';

    public const AUGMENTED_NUCLEOTECH = 'augmented';

    public const DIGITAL_TACTICAL_CONTROL = 'dtc';

    public const GENETIC_EQUITY = 'genetic-equity';

    public const GORDON = 'gordon';

    public const MCCULLOUGH = 'mccullough';

    /**
     * Which Corporation each tree belongs to, by the name the roster gives it in
     * config/running_hot.php.
     *
     * A tree whose Corporation is not in the game - because Control renamed it,
     * or built a roster of their own - still seeds. Its technologies simply
     * belong to no Corporation, which is the same choice
     * App\Actions\CreateDefaultFacilities makes for a Facility whose type has
     * gone: better a catalogue Control can reassign than a silent omission.
     *
     * @return array<string, string>
     */
    public static function corporationNames(): array
    {
        return [
            self::AUGMENTED_NUCLEOTECH => 'Augmented Nucleotech',
            self::DIGITAL_TACTICAL_CONTROL => 'Digital Tactical Control',
            self::GENETIC_EQUITY => 'Genetic Equity',
            self::GORDON => 'Gordon',
            self::MCCULLOUGH => 'McCullough Calibrated Mechanical',
        ];
    }

    /**
     * @return array<int, array{
     *     code: string,
     *     name: string,
     *     tree: string,
     *     split_group: string|null,
     *     split_piece: int|null,
     *     split_pieces: int|null,
     *     description: string|null,
     *     effect: string|null,
     *     cog_cost: int,
     *     brain_cost: int,
     *     leaf_cost: int,
     *     maths_cost: int,
     *     prerequisites: array<int, string>,
     *     requires_facility_type: string|null,
     *     copy_strength: int|null,
     *     destroy_strength: int|null,
     *     deck_grant: array<string, mixed>|null,
     * }>
     */
    public static function defaults(): array
    {
        return [
            self::technology(
                code: 'RAR001',
                name: 'Hornless cow',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Produces rivers of milk',
                effect: 'Unlock: Amdumbla',
                cost: ['cog' => 8, 'brain' => 16, 'leaf' => 6, 'maths' => 2],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR017',
                name: 'Forest creature',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Seductive and secretive',
                effect: 'Unlock: Hulder',
                cost: ['brain' => 6, 'maths' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR018',
                name: 'Sleeping horse',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Bringer of bad dreams',
                effect: 'Unlock: Nattmara',
                cost: ['cog' => 10, 'leaf' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR019',
                name: 'Luring spirit',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Violins and thin ice',
                effect: 'Unlock: Nøkken',
                cost: ['brain' => 10, 'leaf' => 10, 'maths' => 10],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR020',
                name: 'Musician spirit',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Teacher for a goat',
                effect: 'Unlock: Fossegrim',
                cost: ['cog' => 26],
                prerequisites: ['Luring spirit'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR021',
                name: 'Swedish wight',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Borrower of cattle, returned with more milk',
                effect: 'Unlock: Vittra',
                cost: ['brain' => 12, 'leaf' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR022',
                name: 'Mistress of the forest',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Woman from the front, hollow back and tail',
                effect: 'Unlock: Skogsrå',
                cost: ['leaf' => 20, 'maths' => 14],
                prerequisites: ['Forest creature'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR023',
                name: 'Backward hooves',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'The most beautiful grey horse…',
                effect: 'Unlock: Ykur',
                cost: ['cog' => 10, 'leaf' => 10],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR024',
                name: 'Glacial worm',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Iclandic Nessie?',
                effect: 'Unlock: Lagarfljót worm',
                cost: ['brain' => 10, 'leaf' => 10],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR025',
                name: 'Child eating giant',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Hunter of naughty children',
                effect: 'Unlock: Grýla',
                cost: ['leaf' => 10, 'maths' => 8],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR026',
                name: 'Repulsive husband',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: '3rd husband',
                effect: 'Unlock: leppalúði',
                cost: ['brain' => 14, 'maths' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR027',
                name: 'Christmas pranksters',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'T\'is the season',
                effect: 'Unlock: Yule Lads',
                cost: ['cog' => 40, 'leaf' => 10],
                prerequisites: ['Child eating giant', 'Repulsive husband'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR028',
                name: 'Christmas cat',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Eater of the last fashion trend',
                effect: 'Unlock: Jólakötturinn',
                cost: ['brain' => 10, 'leaf' => 40],
                prerequisites: ['Child eating giant', 'Repulsive husband'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR029',
                name: 'Stories of kings',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Let us tell you a tale…',
                effect: 'Unlock: Heimskringla',
                cost: ['cog' => 20, 'leaf' => 16, 'maths' => 20],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR030',
                name: 'Invading sorcerer',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Scout of Bluetooth',
                effect: 'Unlock: Terrible whale',
                cost: ['brain' => 18, 'maths' => 18],
                prerequisites: ['Stories of kings'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR031',
                name: 'Eastern fjord',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Oceans burned with its breath, thunder clapped with its wings',
                effect: 'Unlock: Dragon wight',
                cost: ['brain' => 38, 'leaf' => 30],
                prerequisites: ['Stories of kings', 'Invading sorcerer'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR032',
                name: 'Northern fjord',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Wingspan that stretched between the highest mountains',
                effect: 'Unlock: Eyjafjörður griffin',
                cost: ['leaf' => 30, 'maths' => 30],
                prerequisites: ['Stories of kings', 'Invading sorcerer'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR033',
                name: 'Western fjord',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Horns of bronze, hard as stone',
                effect: 'Unlock: Breiðafjörður bull',
                cost: ['cog' => 16, 'brain' => 16, 'leaf' => 16, 'maths' => 16],
                prerequisites: ['Stories of kings', 'Invading sorcerer'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR034',
                name: 'Southern peninsula',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Taller than the hilltops',
                effect: 'Unlock: Vikarsskeið giant',
                cost: ['cog' => 20, 'brain' => 24, 'leaf' => 12, 'maths' => 8],
                prerequisites: ['Stories of kings', 'Invading sorcerer'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR035',
                name: 'Power (Part 1/4)',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Starting tech',
                effect: 'Unlock: Power facility. You may build a power canister for 5 credits',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR036',
                name: 'Power (Part 2/4)',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Starting tech',
                effect: 'Unlock: Power facility. You may build a power canister for 5 credits',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR037',
                name: 'Power (Part 3/4)',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Starting tech',
                effect: 'Unlock: Power facility. You may build a power canister for 5 credits',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR038',
                name: 'Power (Part 4/4)',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Starting tech',
                effect: 'Unlock: Power facility. You may build a power canister for 5 credits',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR057',
                name: 'Power economy',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'I think we can be more efficient in our power usages',
                effect: 'When you are directing security at a facility, you may activate another '
                    .'cyber protection in that facility. Increase income',
                cost: ['brain' => 10, 'maths' => 14],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR063',
                name: 'Enhanced power economy',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'There’s more in those generators, I can feel it',
                effect: 'You may activate an additional cyber protection in all your facilities. '
                    .'Increase income',
                cost: ['cog' => 16, 'leaf' => 8],
                prerequisites: ['Power economy'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR065',
                name: 'Forest seductress',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Long cow’s tail, under a skirt',
                effect: 'Unlock: Huldra',
                cost: ['cog' => 16, 'leaf' => 16, 'maths' => 8],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR097',
                name: 'ANTHIL',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'Nobody can hear us',
                effect: 'Create a deployable zone of secrecy',
                cost: ['cog' => 5, 'brain' => 5, 'maths' => 5],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR098',
                name: 'Distributed load',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'So many people, so little time',
                effect: 'The efficiency of your power grid is increased – increase income',
                cost: ['cog' => 6, 'leaf' => 8, 'maths' => 6],
                prerequisites: ['Enhanced power economy'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR099',
                name: 'Battery storage',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'We can build so much more',
                effect: 'You are now selling battery storage. Increase income',
                cost: ['cog' => 4, 'leaf' => 6],
                prerequisites: ['Enhanced power economy'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RAR100',
                name: 'Transportation',
                tree: self::AUGMENTED_NUCLEOTECH,
                description: 'With this, we could rule the roads',
                effect: 'Begin manufacture of electric vehicles',
                cost: ['cog' => 6, 'brain' => 8, 'leaf' => 7],
                prerequisites: ['Battery storage'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR039',
                name: 'Arms (Part 1/4)',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Starting tech',
                effect: 'Unlock: Arms facility',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR040',
                name: 'Arms (Part 2/4)',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Starting tech',
                effect: 'Unlock: Arms facility',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR041',
                name: 'Arms (Part 3/4)',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Starting tech',
                effect: 'Unlock: Arms facility',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR042',
                name: 'Arms (Part 4/4)',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Starting tech',
                effect: 'Unlock: Arms facility',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR058',
                name: 'Entrapment',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Maybe we can trick runners into running into dangerous servers?',
                effect: 'Unlock: Honey pot',
                cost: ['brain' => 6, 'leaf' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR062',
                name: 'Advanced entrapment',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'I think we can be a little more...dangerous',
                effect: 'Unlock: Honey bomb',
                cost: ['leaf' => 14, 'maths' => 16],
                prerequisites: ['Entrapment'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR076',
                name: 'Tail \'Em',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'If they come in, surely we can follow them out.',
                effect: 'Unlock: ID facility',
                cost: ['cog' => 10, 'leaf' => 10],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR077',
                name: 'Catch \'Em',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Now that we\'ve got our eyes on them, we can do something with it.',
                effect: 'Unlock: Beat Cop',
                cost: ['brain' => 14, 'maths' => 14],
                prerequisites: ['Tail \'Em'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR078',
                name: 'Cut Them Off',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Don\'t you think they\'ve had enough help?',
                effect: 'Twice a turn, you may pay 7 credits to choose a tagged runner and '
                    .'prevent them from buying from the marketplace.',
                cost: ['cog' => 18, 'maths' => 10],
                prerequisites: ['Tail \'Em'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR079',
                name: 'Burn Baby Burn',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Disco inferno!',
                effect: 'Twice a turn, you may pay 7 credits to choose a tagged runner and '
                    .'inflict them with 5 wounds.',
                cost: ['cog' => 20, 'brain' => 18],
                prerequisites: ['Cut Them Off'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR080',
                name: 'Starting Small',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Just so these pack a little more punch.',
                effect: 'You\'ve created enhanced firearms. Income increased.',
                cost: ['brain' => 20, 'leaf' => 8],
                requiresFacility: FacilityTypeBlueprint::ARMS,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR081',
                name: 'Artificial Reinforcements',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Who needs people when you\'ve got robots?',
                effect: 'Unlock: Assault Drones',
                cost: ['leaf' => 10, 'maths' => 10],
                prerequisites: ['Starting Small'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR082',
                name: 'Geo Mapping',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Tag and bag.',
                effect: 'If a runner runs on any of your facilities, you can pay four credits to '
                    .'give them one tag.',
                cost: ['brain' => 14, 'maths' => 12],
                requiresFacility: FacilityTypeBlueprint::ID_FACILITY,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR083',
                name: 'War Games',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Is it a game or is it real?',
                effect: 'Unlock: Missile Network facility',
                cost: ['cog' => 34, 'brain' => 34, 'maths' => 16],
                prerequisites: ['Starting Small'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR084',
                name: 'Infiltration',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Hiding in plain sight.',
                effect: 'You\'ve created camouflage technology that can be woven into any outfit. '
                    .'Increase income.',
                cost: ['brain' => 30, 'leaf' => 6, 'maths' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR085',
                name: 'Subjugation',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'The perfect killing machines.',
                effect: 'Unlock: SpecOp Drones',
                cost: ['brain' => 14, 'leaf' => 14],
                prerequisites: ['Artificial Reinforcements'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR086',
                name: 'Equipment Production',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Runner equipment is very shoddy; let\'s fix that',
                effect: 'Unlock: Equipment facility',
                cost: ['cog' => 12, 'brain' => 6, 'maths' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR087',
                name: 'Improved Equipment',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Runners might pay well for good quality equipment',
                effect: 'Equipment Facilities can now produce Super Boosts and Armour for 4 '
                    .'credits each',
                cost: ['cog' => 16, 'brain' => 6, 'maths' => 10],
                prerequisites: ['Equipment Production'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR088',
                name: 'Master Equipment',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'I think we can make even greater stuff',
                effect: 'Equipment Facilities can now produce Beam Blades, Cyber-Brain '
                    .'Intergrators and Ultra Boosts for 7 credits each',
                cost: ['cog' => 20, 'brain' => 12, 'maths' => 10],
                prerequisites: ['Improved Equipment'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR089',
                name: 'The Walls have Eyes',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Knowledge is power and there\'s nothing wrong with having a peek, right?',
                effect: 'Once a turn, you may take a Reconnaissance action. Roll 4d8 – if you '
                    .'roll more 6s, 7s and 8s than you do 1s and 2s then you are successful',
                cost: ['cog' => 6, 'brain' => 12, 'maths' => 8],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR090',
                name: 'Extra Eyes',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'We need a better look so let\'s look from the inside',
                effect: 'For every DTC unique protection card or tech card that you have produced '
                    .'and given to another corp, you get +2d on your reconnaisance rolls '
                    .'against them',
                cost: ['brain' => 20, 'maths' => 12],
                prerequisites: ['The Walls have Eyes'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR091',
                name: 'Unkown Eyes',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'They won\'t mind if we use their eyes as well',
                effect: 'Once per turn, you make an extra Reconnaissance action against a corp if '
                    .'a runner carrying your gear makes a run against that corp',
                cost: ['cog' => 12, 'brain' => 16, 'maths' => 6],
                prerequisites: ['The Walls have Eyes', 'Equipment Production'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR092',
                name: 'Unfortunate Malfunction',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Such a shame if it just stopped working at the wrong time',
                effect: 'You can give any number of runners a single use equipment card called '
                    .'"??? bypass" where ??? is the name of a DTC unique protection card. That '
                    .'equipment can be used to automatically succeed against the named '
                    .'protection card',
                cost: ['cog' => 10, 'brain' => 20, 'leaf' => 6, 'maths' => 20],
                prerequisites: ['Extra Eyes'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RDR093',
                name: 'High Power Personel',
                tree: self::DIGITAL_TACTICAL_CONTROL,
                description: 'Bigger guns means better protection',
                effect: 'Unlock: Armoured Guards',
                cost: ['cog' => 12, 'leaf' => 8, 'maths' => 12],
                prerequisites: ['Starting Small'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR043',
                name: 'Miracle Genetics (Part 1/4)',
                tree: self::GENETIC_EQUITY,
                description: 'Starting tech',
                effect: 'For each research facility you have, gain 2 credits during team time',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR044',
                name: 'Miracle Genetics (Part 2/4)',
                tree: self::GENETIC_EQUITY,
                description: 'Starting tech',
                effect: 'For each research facility you have, gain 2 credits during team time',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR045',
                name: 'Miracle Genetics (Part 3/4)',
                tree: self::GENETIC_EQUITY,
                description: 'Starting tech',
                effect: 'For each research facility you have, gain 2 credits during team time',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR046',
                name: 'Miracle Genetics (Part 4/4)',
                tree: self::GENETIC_EQUITY,
                description: 'Starting tech',
                effect: 'For each research facility you have, gain 2 credits during team time',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR047',
                name: 'Interspaced short palindromic repeats',
                tree: self::GENETIC_EQUITY,
                description: 'We must build on the shoulders of giants',
                effect: 'You can sell CRISPR kits to the populace. You will get an increase to '
                    .'your income',
                cost: ['brain' => 8, 'maths' => 16],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR048',
                name: 'Enzyme upgrade',
                tree: self::GENETIC_EQUITY,
                description: 'Mutations are needed',
                effect: 'Your CRISPR kits are more effective and desirable',
                cost: ['cog' => 6, 'brain' => 6, 'leaf' => 6, 'maths' => 8],
                prerequisites: ['Interspaced short palindromic repeats'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR049',
                name: 'Mutation corrections',
                tree: self::GENETIC_EQUITY,
                description: 'Base editing is the way forward',
                effect: 'Your CRISPR kits can be more programmed more effectively',
                cost: ['brain' => 14, 'maths' => 20],
                prerequisites: ['Interspaced short palindromic repeats'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR050',
                name: 'DNA testing',
                tree: self::GENETIC_EQUITY,
                description: 'We know so much, but do we know enough?',
                effect: 'You can now offer genetic testing',
                cost: ['cog' => 6, 'brain' => 10, 'leaf' => 16],
                prerequisites: ['Enzyme upgrade', 'Mutation corrections'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR051',
                name: 'Deoxyribonucleic editing',
                tree: self::GENETIC_EQUITY,
                description: 'We can definitely do more with this',
                effect: 'You can now offer basic gene-editing',
                cost: ['brain' => 6, 'leaf' => 16],
                prerequisites: ['Enzyme upgrade', 'Mutation corrections', 'DNA testing'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR052',
                name: 'Crossspeciesm',
                tree: self::GENETIC_EQUITY,
                description: 'We have the power to begin doing this',
                effect: 'You are able to splice DNA from small mammals into other small mammals',
                prerequisites: ['Deoxyribonucleic editing'],
                requiresFacility: FacilityTypeBlueprint::RESEARCH,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR053',
                name: 'First cross species',
                tree: self::GENETIC_EQUITY,
                description: 'Trial number 1',
                effect: 'Your experiment is successful – no other effect',
                cost: ['cog' => 14],
                prerequisites: ['Crossspeciesm'],
                requiresFacility: FacilityTypeBlueprint::RESEARCH,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR054',
                name: 'Second cross species',
                tree: self::GENETIC_EQUITY,
                description: 'Trial number 2',
                effect: 'Your experiment is successful – no other effect',
                cost: ['leaf' => 14],
                prerequisites: ['Crossspeciesm'],
                requiresFacility: FacilityTypeBlueprint::RESEARCH,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR055',
                name: 'Third cross species',
                tree: self::GENETIC_EQUITY,
                description: 'Trial number 3',
                effect: 'Your experiment is successful – no other effect',
                cost: ['brain' => 14],
                prerequisites: ['Crossspeciesm'],
                requiresFacility: FacilityTypeBlueprint::RESEARCH,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR056',
                name: 'Advanced cross-speciesism',
                tree: self::GENETIC_EQUITY,
                description: 'We understand what we’re doing now',
                effect: 'You are able to splice DNA from any animal into another',
                cost: ['cog' => 20, 'brain' => 24, 'leaf' => 12, 'maths' => 14],
                prerequisites: ['First cross species', 'Second cross species', 'Third cross species'],
                requiresFacility: FacilityTypeBlueprint::RESEARCH,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR059',
                name: 'Data collection',
                tree: self::GORDON,
                description: 'We\'ve got a captive audience, but what do they want?',
                effect: 'Your income is increased',
                cost: ['leaf' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR060',
                name: 'Targeted advertising',
                tree: self::GORDON,
                description: 'Now we know that they want, let’s rinse them',
                effect: 'Your income is increased',
                cost: ['brain' => 12, 'maths' => 6],
                prerequisites: ['Data collection'],
                requiresFacility: FacilityTypeBlueprint::CORPORATE,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR061',
                name: 'Advanced advertising',
                tree: self::GORDON,
                description: 'We need to tell them what they want',
                effect: 'You can spend credits to trigger increased sales of a product of your '
                    .'choice',
                cost: ['brain' => 14, 'maths' => 12],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR064',
                name: 'Overseers',
                tree: self::GORDON,
                description: 'There’s always more to know',
                effect: 'Once a turn, you may take a Reconnaissance action. Roll 8d8 – if you '
                    .'roll 6s, 7s and 8s than you do 1s and 2s then you are successful',
                prerequisites: ['Advanced advertising', 'Upload stability'],
                requiresFacility: FacilityTypeBlueprint::CORPORATE,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR066',
                name: 'Face Off',
                tree: self::GORDON,
                description: 'Now we\'re seeing eye to eye.',
                effect: 'You can create still digital recreations of people.',
                cost: ['cog' => 6, 'brain' => 6, 'maths' => 8],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR067',
                name: 'Who\'s The Fairest',
                tree: self::GORDON,
                description: 'Why hire talent when you can make it?',
                effect: 'You can now create unique virtual celebrities/personalities. Permanently '
                    .'boost other forms of income by 25% so long as you have this technology.',
                cost: ['cog' => 6, 'brain' => 10, 'leaf' => 6, 'maths' => 12],
                prerequisites: ['Face Off'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR068',
                name: 'You\'ve Got A Friend In Me',
                tree: self::GORDON,
                description: 'Everyone gets a little lonely.',
                effect: 'You can now sell customizable virtual companions. Increase income.',
                cost: ['cog' => 8, 'brain' => 16, 'leaf' => 18, 'maths' => 14],
                prerequisites: ['Face Off'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR069',
                name: 'Mirror, Mirror',
                tree: self::GORDON,
                description: 'Don\'t look too closely.',
                effect: 'Unlock: Doppleganger',
                cost: ['cog' => 10, 'brain' => 26, 'leaf' => 26, 'maths' => 26],
                prerequisites: ['Who\'s The Fairest', 'Understanding the Psyche'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR070',
                name: 'The Capture',
                tree: self::GORDON,
                description: 'A perfect snapshot in time.',
                effect: 'You can near perfectly alter digital images and videos to implicate '
                    .'others.',
                cost: ['brain' => 34, 'leaf' => 10, 'maths' => 20],
                prerequisites: ['You\'ve Got A Friend In Me', 'Understanding the Psyche'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR071',
                name: 'Constant Advertising',
                tree: self::GORDON,
                description: 'Time to get a leg-up in the corporate war.',
                effect: 'Your income is increased.',
                cost: ['cog' => 24, 'brain' => 30, 'maths' => 24],
                prerequisites: ['Targeted advertising'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR072',
                name: 'Understanding the Psyche',
                tree: self::GORDON,
                description: 'If we want to get to people, we need to get to know people.',
                effect: 'You\'ve gained a better understanding of how people work.',
                cost: ['brain' => 8, 'leaf' => 10],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR073',
                name: 'Subliminal Advertising',
                tree: self::GORDON,
                description: 'They won\'t know what hit them.',
                effect: 'You can now insert subliminal messaging into any of your media output.',
                cost: ['brain' => 20, 'leaf' => 26, 'maths' => 14],
                prerequisites: ['Understanding the Psyche', 'Targeted advertising'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR074',
                name: 'I Spy',
                tree: self::GORDON,
                description: 'She sees you when you\'re sleeping...',
                effect: 'Unlock: SAIren, AIdol',
                cost: ['cog' => 20, 'leaf' => 20],
                prerequisites: ['You\'ve Got A Friend In Me'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR075',
                name: 'Playground Games',
                tree: self::GORDON,
                description: 'You\'re it!',
                effect: 'Unlock: Georgie',
                cost: ['brain' => 20, 'leaf' => 6, 'maths' => 14],
                prerequisites: ['You\'ve Got A Friend In Me'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RGR094',
                name: 'Genetic Equity story',
                tree: self::GORDON,
                description: 'Rosales seems to be hiding something',
            ),
            self::technology(
                code: 'RGR095',
                name: 'Skarlo',
                tree: self::GORDON,
                description: 'A freelancer is looking for Skarlo',
            ),
            self::technology(
                code: 'RGR096',
                name: 'Slow roll',
                tree: self::GORDON,
                description: 'There’s rumours of a new virus being created',
            ),
            self::technology(
                code: 'RMR002',
                name: 'People of the mounds',
                tree: self::MCCULLOUGH,
                description: 'Invisible, from the mounds',
                effect: 'Unlock: aos sí',
                cost: ['cog' => 6, 'leaf' => 8],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR003',
                name: 'Scottish death',
                tree: self::MCCULLOUGH,
                description: '3 barks...',
                effect: 'Unlock: Cú-síth',
                cost: ['brain' => 8, 'leaf' => 6],
                prerequisites: ['People of the mounds'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR004',
                name: 'King of the cats',
                tree: self::MCCULLOUGH,
                description: 'A witch?',
                effect: 'Unlock: Cat síth',
                cost: ['cog' => 8, 'leaf' => 10, 'maths' => 8],
                prerequisites: ['People of the mounds'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR005',
                name: 'Welsh death',
                tree: self::MCCULLOUGH,
                description: 'Migrating geese?',
                effect: 'Unlock: Cŵn Annwn',
                cost: ['cog' => 6, 'brain' => 2, 'leaf' => 10, 'maths' => 8],
                prerequisites: ['People of the mounds'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR006',
                name: 'Irish otter',
                tree: self::MCCULLOUGH,
                description: 'Protective fur',
                effect: 'Unlock: Dobhar-chú',
                cost: ['cog' => 12, 'brain' => 8, 'leaf' => 14],
                prerequisites: ['People of the mounds'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR007',
                name: 'Fire dogs',
                tree: self::MCCULLOUGH,
                description: 'Evil death',
                effect: 'Unlock: Hellhound',
                cost: ['brain' => 18, 'leaf' => 18],
                prerequisites: ['Welsh death', 'Scottish death'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR008',
                name: 'Deadly snake',
                tree: self::MCCULLOUGH,
                description: 'Monstrous, deadly, challenger of the gods',
                effect: 'Unlock: Typhon',
                cost: ['cog' => 24, 'leaf' => 26],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR009',
                name: 'Snake woman',
                tree: self::MCCULLOUGH,
                description: 'She-viper',
                effect: 'Unlock: Echidna',
                cost: ['brain' => 26, 'leaf' => 16, 'maths' => 14],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR010',
                name: 'Hound of Hades',
                tree: self::MCCULLOUGH,
                description: 'Captured by the god',
                effect: 'Unlock: Cerberus',
                cost: ['cog' => 26, 'brain' => 14, 'leaf' => 26],
                prerequisites: ['Deadly snake', 'Snake woman', 'Fire dogs'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR011',
                name: 'Cattle dog',
                tree: self::MCCULLOUGH,
                description: 'Protector of cattle',
                effect: 'Unlock: Orthrus',
                cost: ['cog' => 38, 'leaf' => 6],
                prerequisites: ['Deadly snake', 'Snake woman', 'Fire dogs'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR012',
                name: 'Factory (Part 1/3)',
                tree: self::MCCULLOUGH,
                description: 'Starting tech',
                effect: 'Unlock: Factory facility. Unlock: Mini-factory facility',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR013',
                name: 'Factory (Part 2/3)',
                tree: self::MCCULLOUGH,
                description: 'Starting tech',
                effect: 'Unlock: Factory facility. Unlock: Mini-factory facility',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR014',
                name: 'Factory (Part 3/3)',
                tree: self::MCCULLOUGH,
                description: 'Starting tech',
                effect: 'Unlock: Factory facility. Unlock: Mini-factory facility',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR015',
                name: 'Construction leader (Part 1/2)',
                tree: self::MCCULLOUGH,
                description: 'Starting tech',
                effect: 'You receive a discount of 2 credits when building a facility. You may '
                    .'build facilities for other corporations',
                requiresFacility: FacilityTypeBlueprint::FACTORY,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR016',
                name: 'Construction leader (Part 2/2)',
                tree: self::MCCULLOUGH,
                description: 'Starting tech',
                effect: 'You receive a discount of 2 credits when building a facility. You may '
                    .'build facilities for other corporations',
                requiresFacility: FacilityTypeBlueprint::FACTORY,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR101',
                name: 'Prefabrication',
                tree: self::MCCULLOUGH,
                description: 'We can do everything in advance',
                effect: 'Receive an additional 1 credit discount when building a facility',
                cost: ['cog' => 8, 'maths' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR102',
                name: 'Automated build',
                tree: self::MCCULLOUGH,
                description: 'We don’t need people!',
                effect: 'You may replace some of your workforce with automatic drones',
                cost: ['brain' => 8, 'leaf' => 6, 'maths' => 4],
                prerequisites: ['Prefabrication'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR103',
                name: 'JIT Delivery',
                tree: self::MCCULLOUGH,
                description: 'Our building work could be automated',
                effect: 'You may replace some of your workforce with automatic drones that can '
                    .'react quickly to any new building work',
                cost: ['cog' => 6, 'brain' => 6, 'leaf' => 6, 'maths' => 6],
                prerequisites: ['Automated build', 'Incursions into AI'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RMR104',
                name: 'Building network',
                tree: self::MCCULLOUGH,
                description: 'Just let them go!',
                effect: 'You may replace your engineering managers with automatic drones that can '
                    .'predict any new building work',
                cost: ['cog' => 10, 'leaf' => 13, 'maths' => 8],
                prerequisites: ['A new dawn', 'JIT Delivery'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR001',
                name: 'Deer horns',
                tree: self::COMMON,
                description: 'We all remember the tale of the horned deer and lion, let’s build on it',
                effect: 'Unlock: Keresh',
                cost: ['brain' => 10, 'leaf' => 8],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR002',
                name: 'Lion of giants',
                tree: self::COMMON,
                description: 'The deer sleeps, does the lion roar?',
                effect: 'Unlock: Tigris',
                cost: ['brain' => 16, 'leaf' => 12],
                prerequisites: ['Deer horns'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR003',
                name: 'Flying deer',
                tree: self::COMMON,
                description: 'What can we find in the forest of dreams?',
                effect: 'Unlock: Peryton',
                cost: ['cog' => 16, 'brain' => 30, 'leaf' => 24, 'maths' => 8],
                prerequisites: ['Forests of dreams'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR004',
                name: 'Forests of dreams',
                tree: self::COMMON,
                description: 'The deer and lion should live together in peace',
                effect: 'Unlock: Bei Ilai',
                cost: ['cog' => 10, 'brain' => 20, 'leaf' => 16],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR005',
                name: 'Flying lion',
                tree: self::COMMON,
                description: 'What can we find in the forest of dreams?',
                effect: 'Unlock: Ziz',
                cost: ['cog' => 8, 'brain' => 30, 'leaf' => 24, 'maths' => 20],
                prerequisites: ['Eagled lion'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR006',
                name: 'Eagled lion',
                tree: self::COMMON,
                description: 'What can we find in the forest of dreams?',
                effect: 'Unlock: Griffin',
                cost: ['cog' => 8, 'brain' => 30, 'leaf' => 24, 'maths' => 20],
                prerequisites: ['Forests of dreams'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR007',
                name: 'Birds of prey',
                tree: self::COMMON,
                description: 'What can we find in the forest of dreams?',
                effect: 'Unlock: Turul',
                prerequisites: ['Forests of dreams'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR008',
                name: 'Divine lion',
                tree: self::COMMON,
                description: 'What can we find in the forest of dreams?',
                effect: 'Unlock: Anzû',
                cost: ['cog' => 20, 'brain' => 30, 'leaf' => 40, 'maths' => 20],
                prerequisites: ['Eagled lion'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR009',
                name: 'Sleeping birds',
                tree: self::COMMON,
                description: 'We need to slow down the runners',
                effect: 'Unlock: Nachtkrapp',
                cost: ['brain' => 12, 'maths' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR010',
                name: 'Mythical farm',
                tree: self::COMMON,
                description: 'There’s a collection of mythology that we aren’t considering',
                effect: 'Collect Mythical research from research control',
                cost: ['cog' => 10, 'brain' => 16, 'leaf' => 16, 'maths' => 10],
                requiresFacility: FacilityTypeBlueprint::RESEARCH,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR011',
                name: 'Metal cow',
                tree: self::COMMON,
                description: 'They had some great ideas back in the day of the Ancient Greeks, didn’t '
                    .'they?',
                effect: 'Unlock: Brazen bull',
                cost: ['brain' => 12, 'maths' => 6],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR012',
                name: 'Mane bull',
                tree: self::COMMON,
                description: 'An escaping bull',
                effect: 'Unlock: Bonnacon',
                cost: ['cog' => 8],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR013',
                name: 'White marsh',
                tree: self::COMMON,
                description: 'The empires of old discovered these',
                effect: 'Unlock: Baì Zè',
                cost: ['cog' => 20, 'brain' => 12, 'maths' => 8],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR014',
                name: 'Human bull',
                tree: self::COMMON,
                description: 'The famous example',
                effect: 'Unlock: Minotaur',
                cost: ['cog' => 12, 'brain' => 18, 'leaf' => 8, 'maths' => 6],
                prerequisites: ['Mythical farm', 'Mane bull'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR015',
                name: 'Multicoloured horns',
                tree: self::COMMON,
                description: 'Rejoice in its many colours',
                effect: 'Unlock: Tachash',
                cost: ['cog' => 10, 'brain' => 18],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR016',
                name: 'Panther bull',
                tree: self::COMMON,
                description: 'Eater of those who protected their family',
                effect: 'Unlock: Bicorn',
                cost: ['cog' => 20, 'leaf' => 6, 'maths' => 6],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR017',
                name: 'Starving panther bull',
                tree: self::COMMON,
                description: 'Eater of those who did not protect their family',
                effect: 'Unlock: Chichevache',
                cost: ['brain' => 16, 'leaf' => 16],
                prerequisites: ['Panther bull'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR018',
                name: 'Muscular bull',
                tree: self::COMMON,
                description: 'Protector of jewels',
                effect: 'Unlock: Sarangay',
                cost: ['cog' => 8, 'leaf' => 6, 'maths' => 6],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR019',
                name: 'Preparation rooster',
                tree: self::COMMON,
                description: 'Wake the heroes...',
                effect: 'Unlock: Gullinkambi',
                cost: ['brain' => 10, 'maths' => 10],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR020',
                name: 'Warning rooster',
                tree: self::COMMON,
                description: 'Forest deceiver...',
                effect: 'Unlock: Fjalar',
                cost: ['brain' => 18],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR021',
                name: 'Alert rooster',
                tree: self::COMMON,
                description: 'Rust red...',
                effect: 'Unlock: Rooster from Hel',
                cost: ['cog' => 6, 'leaf' => 10],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR022',
                name: 'French rooster',
                tree: self::COMMON,
                description: 'Who knows what this can symbolise now?',
                effect: 'Unlock: Gallic rooster',
                cost: ['brain' => 16, 'maths' => 6],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR023',
                name: 'Fire chicken',
                tree: self::COMMON,
                description: 'Cold flames come from the mountain',
                effect: 'Unlock: Basan',
                cost: ['cog' => 2, 'brain' => 18, 'leaf' => 10],
                prerequisites: ['Mythical farm'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR024',
                name: 'Incursions into AI',
                tree: self::COMMON,
                description: 'It\'s getting tedious to design the protection protocols - maybe we can '
                    .'start to speed things up?',
                effect: 'You may place an additional cyber protection in each of your facilities',
                cost: ['cog' => 12, 'leaf' => 6],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR025',
                name: 'AI helpers',
                tree: self::COMMON,
                description: 'I think our AI could do more',
                effect: 'Unlock: Bindy',
                cost: ['cog' => 16, 'leaf' => 18],
                prerequisites: ['Incursions into AI'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR026',
                name: 'Packet sniffer',
                tree: self::COMMON,
                description: 'With more training, we could catch intruders!',
                effect: 'Unlock: Tobius',
                cost: ['cog' => 14, 'brain' => 10],
                prerequisites: ['Incursions into AI'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR027',
                name: 'Confucius Conjecture',
                tree: self::COMMON,
                description: 'Confucius says that we learn by experience, imitation and reflection. '
                    .'Can AI do it?',
                effect: 'Single payment if first to research',
                cost: ['brain' => 20, 'leaf' => 30, 'maths' => 26],
                prerequisites: ['Incursions into AI'],
                requiresFacility: FacilityTypeBlueprint::RESEARCH,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR028',
                name: 'A new dawn',
                tree: self::COMMON,
                description: 'How fast can they learn?',
                effect: 'Increase challenge strength of all cyber protection by 1',
                cost: ['brain' => 16, 'leaf' => 18],
                prerequisites: ['AI pre-school'],
                requiresFacility: FacilityTypeBlueprint::AI_SCHOOL,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR029',
                name: 'AI pre-school',
                tree: self::COMMON,
                description: 'We need a specific place to research how our AI is learning',
                effect: 'Unlock: AI School facility',
                cost: ['leaf' => 26, 'maths' => 30],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR030',
                name: 'Internet link',
                tree: self::COMMON,
                description: 'Maybe we can get a better uplink',
                effect: 'When you are directing security at a facility, you may increase the '
                    .'challenge of a single cyber protection in that facility by 1 for this '
                    .'turn',
                cost: ['cog' => 10, 'brain' => 10, 'maths' => 10],
                requiresFacility: FacilityTypeBlueprint::SECURITY,
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR031',
                name: 'Storage',
                tree: self::COMMON,
                description: 'We can do better with our compression algorithms!',
                effect: 'Unlock: Data card',
                cost: ['brain' => 18, 'maths' => 10],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR032',
                name: 'Upload stability',
                tree: self::COMMON,
                description: 'Can we utilise these uplinks more?',
                effect: 'When you choose a facility to direct security, you may take a cyber '
                    .'protection from a different facility and add it to this facility for the '
                    .'rest of the turn',
                cost: ['cog' => 26, 'brain' => 26, 'maths' => 10],
                prerequisites: ['Internet link', 'Storage'],
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR033',
                name: 'Honey bomb',
                tree: self::COMMON,
                effect: 'When a runner accesses this card, they instead make a hack (8) check. On '
                    .'failure, deal 3 wounds to the Run Leader. Return to Control',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR034',
                name: 'Honey pot',
                tree: self::COMMON,
                effect: 'When a runner accesses this card, they instead make a hack (4) check. On '
                    .'failure, deal 2 tags to all members of the run. Return to Control',
                copyStrength: 4,
                destroyStrength: 4,
            ),
            self::technology(
                code: 'RSR035',
                name: 'Research deck',
                tree: self::COMMON,
                description: 'Spend 4 research credits in any suit to add a “No single” card to your '
                    .'research deck in that suit. You choose a value for the card between 3-5',
                deckGrant: self::deckGrant([4], 3, 5, restriction: ResearchCardRestriction::NoSingle),
            ),
            self::technology(
                code: 'RSR036',
                name: 'Research deck 2',
                tree: self::COMMON,
                description: 'If you have 3 research facilities, you may spend 8 research credits in '
                    .'any suit to add a “No single” card to your research deck in that suit. '
                    .'You choose a value for the card between 6-10',
                deckGrant: self::deckGrant([8], 6, 10, restriction: ResearchCardRestriction::NoSingle, requiresResearchFacilities: 3),
            ),
            self::technology(
                code: 'RSR037',
                name: 'Research deck 3',
                tree: self::COMMON,
                description: 'If you have 5 research facilities, you may spend 6 research credits in '
                    .'any suit and 3 in another to add a card to your research deck in the '
                    .'first suit. You choose a value for the card between 3-5',
                deckGrant: self::deckGrant([6, 3], 3, 5, requiresResearchFacilities: 5),
            ),
            self::technology(
                code: 'RSR038',
                name: 'Research deck 4',
                tree: self::COMMON,
                description: 'If you have 6 research facilities, you may spend 10 research credits in '
                    .'any suit and 5 in another to add a card to your research deck in the '
                    .'first suit. You choose a value for the card between 6-10',
                deckGrant: self::deckGrant([10, 5], 6, 10, requiresResearchFacilities: 6),
            ),
            self::technology(
                code: 'RSR039',
                name: 'Research deck 5',
                tree: self::COMMON,
                description: 'If you have 8 research facilities, you may spend 5 research credits from '
                    .'each suit to add a wild card to your research deck. You choose a value '
                    .'for the card between 3-5',
                deckGrant: self::deckGrant([5, 5, 5, 5], 3, 5, wild: true, requiresResearchFacilities: 8),
            ),
            self::technology(
                code: 'RSR040',
                name: 'Research deck 6',
                tree: self::COMMON,
                description: 'If you have 9 research facilities, you may spend 7 research credits from '
                    .'each suit to add a wild card to your research deck. You choose a value '
                    .'for the card between 6-10',
                deckGrant: self::deckGrant([7, 7, 7, 7], 6, 10, wild: true, requiresResearchFacilities: 9),
            ),
        ];
    }

    /**
     * One technology, as its card is printed.
     *
     * Costs are given as the suits that are not free, so a technology costing
     * nothing in Leaf simply does not mention it. Copy and destroy strengths are
     * what a Runner has to beat to take it (rulebook 3.2.6), and are null on the
     * few rows that are instructions to Research Control rather than cards a Run
     * can reach.
     *
     * @param  array<string, int>  $cost
     * @param  array<int, string>  $prerequisites
     * @param  array<string, mixed>|null  $deckGrant
     * @return array{
     *     code: string,
     *     name: string,
     *     tree: string,
     *     split_group: string|null,
     *     split_piece: int|null,
     *     split_pieces: int|null,
     *     description: string|null,
     *     effect: string|null,
     *     cog_cost: int,
     *     brain_cost: int,
     *     leaf_cost: int,
     *     maths_cost: int,
     *     prerequisites: array<int, string>,
     *     requires_facility_type: string|null,
     *     copy_strength: int|null,
     *     destroy_strength: int|null,
     *     deck_grant: array<string, mixed>|null,
     * }
     */
    private static function technology(
        string $code,
        string $name,
        string $tree,
        ?string $description = null,
        ?string $effect = null,
        array $cost = [],
        array $prerequisites = [],
        ?string $requiresFacility = null,
        ?int $copyStrength = null,
        ?int $destroyStrength = null,
        ?array $deckGrant = null,
    ): array {
        return [
            'code' => $code,
            'name' => $name,
            'tree' => $tree,
            ...self::splitFrom($name),
            'description' => $description,
            'effect' => $effect,
            'cog_cost' => $cost['cog'] ?? 0,
            'brain_cost' => $cost['brain'] ?? 0,
            'leaf_cost' => $cost['leaf'] ?? 0,
            'maths_cost' => $cost['maths'] ?? 0,
            'prerequisites' => $prerequisites,
            'requires_facility_type' => $requiresFacility,
            'copy_strength' => $copyStrength,
            'destroy_strength' => $destroyStrength,
            'deck_grant' => $deckGrant,
        ];
    }

    /**
     * The split technology a card belongs to, read off its printed name
     * (rulebook 3.2.7).
     *
     * "Power (Part 1/4)" is one card of the four that make up Power, and the
     * card says so - so nothing here is invented. A name that does not end that
     * way is a technology of one card, which is nearly all of them.
     *
     * @return array{split_group: string|null, split_piece: int|null, split_pieces: int|null}
     */
    public static function splitFrom(string $name): array
    {
        if (preg_match('/^(?<group>.+) \\(Part (?<piece>\\d+)\\/(?<pieces>\\d+)\\)$/', $name, $matches) !== 1) {
            return ['split_group' => null, 'split_piece' => null, 'split_pieces' => null];
        }

        return [
            'split_group' => $matches['group'],
            'split_piece' => (int) $matches['piece'],
            'split_pieces' => (int) $matches['pieces'],
        ];
    }

    /**
     * One deck customisation entry, as its own row on the tree prints it
     * (rulebook 3.2.3).
     *
     * The amounts are Research Points the player assigns to suits of their
     * choosing, all different - "6 research credits in any suit and 3 in
     * another" is [6, 3], and "5 from each suit" is [5, 5, 5, 5]. The card that
     * comes out takes the suit the first amount was paid in, which is what
     * "in the first suit" means, unless it is wild and has none.
     *
     * @param  array<int, int>  $amounts
     * @return array{
     *     amounts: array<int, int>,
     *     value_min: int,
     *     value_max: int,
     *     wild: bool,
     *     restriction: string|null,
     *     requires_research_facilities: int,
     * }
     */
    private static function deckGrant(
        array $amounts,
        int $valueMin,
        int $valueMax,
        bool $wild = false,
        ?ResearchCardRestriction $restriction = null,
        int $requiresResearchFacilities = 0,
    ): array {
        return [
            'amounts' => $amounts,
            'value_min' => $valueMin,
            'value_max' => $valueMax,
            'wild' => $wild,
            'restriction' => $restriction?->value,
            'requires_research_facilities' => $requiresResearchFacilities,
        ];
    }
}
